# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='SEO заголовок (до 60 симв)')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('embed_code', models.TextField(verbose_name='HTML код видео')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено:')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
            ],
            options={
                'verbose_name_plural': 'Видео',
                'verbose_name': 'Видео',
            },
        ),
    ]
