# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='SEO заголовок (до 60 симв)')),
                ('seodesc', models.CharField(max_length=160, verbose_name='SEO описание(до 160)')),
                ('seokw', models.CharField(max_length=160, verbose_name='SEO Ключевые слова')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Отображается')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено:')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='Видео')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
    ]
