# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 02:11
from __future__ import unicode_literals

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='SEO заголовок (до 60 симв)')),
                ('seodesc', models.CharField(max_length=160, verbose_name='SEO описание (до 160)')),
                ('seokw', models.CharField(max_length=160, verbose_name='SEO Ключевые слова')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.handle_upload, verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('active', models.BooleanField(default=True, verbose_name='Отображается')),
                ('free', models.BooleanField(default=False, verbose_name='Бесплатно')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено:')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.Category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'verbose_name': 'Курс',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='SEO заголовок (до 60 симв)')),
                ('seodesc', models.CharField(max_length=160, verbose_name='SEO описание (до 160)')),
                ('seokw', models.CharField(max_length=160, verbose_name='SEO Ключевые слова')),
                ('slug', models.SlugField(blank=True, verbose_name='Ссылка')),
                ('free', models.BooleanField(default=False, verbose_name='Бесплатно')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено:')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
                ('video', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.Video', verbose_name='Видео')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MyCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='owned', to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Купленные курсы',
                'verbose_name': 'Купленные курсы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=set([('slug', 'course')]),
        ),
    ]
